version: 0.2
phases:
  build:
    commands:
      - curl https://install.python-poetry.org | python -
      - pip3 install -r requirements.txt --target ./libs
cache:
  paths:
    - libs/**/*
artifacts:
  type: zip
  files:
    - libs/**/*
    - .venv
    - src/**/*
    - index.py